### PR TITLE
Make colors configurable, closes #241

### LINKED ISSUE #241: Make color changeable
As described here https://github.com/firegento/firegento-pdf/issues/133#issuecomment-105489449 it would be nice to make the color of "Invoice" and the background color for the table changeable.

### PR DESCRIPTION
**Pull request by Schrank**

### CODE REVIEW

**Comment by sprankhub** [comment]
@Schrank @riker09 could you please solve the conflicts? Thanks!

**Comment by Schrank** [comment]
will do.

**Comment by riker09** [comment]
@Schrank I gave it a try, what do you think? I hope I caught everything. Although I've been a long time git user only recently I started working / collaborating on open source projects. So you can say I'm rather new to this. Please be patient with me if I make any rookie mistakes.

**Comment by Schrank** [comment]
I'm fine teaching git, when I have less work afterwards :D

**Comment by sprankhub** [comment]
https://github.com/firegento/firegento-pdf/commit/dc0c25a0a8ff798a4d65415c41253b136001731e

**Pull request closed without merging**
