### PR TITLE
fix funny translation of "Shipment"

### PR DESCRIPTION
**Pull request by infabo**
"Lieferschein" and not "Versandart" ;)

### CODE REVIEW

**Comment by sprankhub** [comment]
No idea where this translation is used, but thanks anyway :)

**Comment by infabo** [comment]
It is used as headline for the shipment PDF! Please check ;)

**Comment by sprankhub** [comment]
I guess the translation by the German community locale is used if installed. Otherwise, this would have already attracted attention...

**Comment by infabo** [comment]
Should not be the case, look here:

https://github.com/firegento/firegento-pdf/blob/development/src/app/code/community/FireGento/Pdf/Model/Engine/Abstract.php#L483
```
protected function insertHeader(&$page, $order, $document)
    {
        $page->setFillColor($this->colors['black']);

        $mode = $this->getMode();

        $this->_setFontBold($page, 15);

        if ($mode == 'invoice') {
            $title = 'Invoice';
        } elseif ($mode == 'shipment') {
            $title = 'Shipment';
        } else {
            $title = 'Creditmemo';
        }
        $page->drawText(Mage::helper('firegento_pdf')->__($title),
```

It calls the firegento_pdf helper translation.

PS:
https://github.com/riconeitzel/German_LocalePack_de_DE
installed here.

**Pull request merged**
