### PR TITLE
#299 add option select to choose which customer number will be shown

### PR DESCRIPTION
**Pull request by pquerner**
Standard = entity_id of the customer

Feature request from #299

### CODE REVIEW

**Comment by sprankhub** [comment]
Thanks! Could you remove the `@version` and `@since` docs? And could you add a system.xml depends? `customer_number_field` should depend on `show_customer_number`.

**Comment by Schrank** [comment]
And I would prefer if you remove the if and instead set a default in config.xml

**Comment by pquerner** [comment]
@sprankhub @Schrank Done as requested. Please have a look.

**Comment by sprankhub** [comment]
Thanks! Looks good to me. @Schrank?

**Comment by Schrank** [comment]
Sorry for the late feedback, thanks for the patch!

**Pull request merged**
