### PR TITLE
retry mage-test-stand setup if it fails

### PR DESCRIPTION
**Pull request by tkn98**
Reference: #283

See: http://docs.travis-ci.com/user/build-timeouts/

### CODE REVIEW

**Comment by ktomk** [comment]
We fixed the underlying issue upstream in magerun and it is already part of mage test stand (https://github.com/AOEpeople/MageTestStand/commit/f2038ef39cbfd4ccf62cb1f22003f50761f9f396). These updates becamse important for working magento downloads.

**Comment by sprankhub** [comment]
Thanks! Any idea why it fails during the cleanup? It fails during the following command:

    rm -rf /tmp/mageteststand.25JSVJ94

But it also seems that he cleans up too early. It does not finish the test `FireGento_Pdf_Test_Model_CreditmemoTest::itShouldReturnAZendPdf`, but cleans up before. It does not show any error though, which is strange...?

**Comment by sprankhub** [comment]
Idea: Older versions probably fail because Magento < 1.9 does not natively support PHP 5.4 / 5.5...

**Comment by tkn98** [comment]
I don't understand why the exit status differs between the builds. perhaps the download doesn't work. because curl is silenced this is not visible. I will try the one or other thing to make things more visible.

**Comment by Schrank** [comment]
@tkn98 You are great, thanks for your help!

**Comment by tkn98** [comment]
From my end this now looks like a failing test to me: `FireGento_Pdf_Test_Model_CreditmemoTest::itShouldReturnAZendPdf`

This test is failing hard, that means with either a non catchable fatal error (hinted by exit status 255) or even some other hard failure that the php binary crashed. I don't have a good reference at hand that explains all PHP exit codes, I know that 255 is an error.

I can't say whether or not `-d display_errors=1` does actually work as intended in that case. I'd say it normally should work. That then again would be a hint that it's not an error but just a crash.

Both these statements are speculative. So they are of no concrete help and don't take them for real.

Maybe if you look into the test you can find out what is going on.

**Comment by tkn98** [comment]
@sprankhub  The file `build/travis/mageteststand-setup.sh` is not used any longer and can be removed.

**Comment by sprankhub** [comment]
@tkn98 https://github.com/firegento/firegento-pdf/commit/00dde268f51ca644754e16f7828a2096b7fbfd95 ;) Thanks!

By the way, [this](http://serverfault.com/a/153656/270632) is a good explanation of PHP error code 255. I still try to fix the error. I encountered a bug (https://github.com/firegento/firegento-pdf/commit/ccf839d454ce8af1abf607cfbc824e8cf55c1a6d), but it does not seem to be the issue.

**Pull request merged**
