### PR TITLE
fix long addressbar overlapping header

### PR DESCRIPTION
**Pull request by infabo**

### CODE REVIEW

**Comment by Schrank** [comment]
May you have a screenshot, what this is doing?

**Comment by infabo** [comment]
Prevents this:

capture

**Comment by Schrank** [comment]
You do this by pushing everything to the south? Do I understand correctly? My fear is I misunderstand the code and you are pushing the address to the north, but then it won't fit in german window envelopes enymore

**Comment by infabo** [comment]
I'm pushing the headline "Rechnung" and the table-header to the south. Address stays at its place.

**Comment by Schrank** [comment]
Sounds good! Let me have a look (or @sprankhub) 

Thanks for your effort!

**Comment by infabo** [comment]
The reason for this PR is a bad behaviour of _formatAddress method.
As you can see from the screenshot, the address lines get wrapped after 45 characters.
This unfortunately adds - in my special case - two additional line and then the address lines overlap (see screen).
This issue could be addressed within the FireGento_Pdf_Model_Engine_Abstract.

This is the cause for it: 

Mage_Sales_Model_Order_Pdf_Abstract : 225
```
/**
     * Format address
     *
     * @param  string $address
     * @return array
     */
    protected function _formatAddress($address)
    {
        $return = array();
        foreach (explode('|', $address) as $str) {
            foreach (Mage::helper('core/string')->str_split($str, 45, true, true) as $part) {
                if (empty($part)) {
                    continue;
                }
                $return[] = $part;
            }
        }
        return $return;
    }
```

**Comment by Schrank** [comment]
I tend to remove the breaking instead of moving everything else... @sprankhub ?

**Comment by infabo** [comment]
@Schrank I agree.

**Comment by infabo** [comment]
Would solve the overlap - but good looking?

capture

**Comment by sprankhub** [comment]
I guess the breaking is there for a reason - the lines may be too long for German envelopes...

**Comment by Schrank** [comment]
What about just adding a warning, that one should remove tel and fax from the address template? Or just do it? :-)

**Comment by infabo** [comment]
@sprankhub German envelope here!
img_20151021_112709

**Comment by sprankhub** [comment]
I could reproduce the issue and tested the fix - works perfectly. Thanks @infabo!

**Comment by infabo** [comment]
awesome!

**Pull request merged**
